# Copyright 2025 DEVSIM LLC
#
# SPDX-License-Identifier: Apache-2.0

"""
JEM2025_plot_figures.py - Generate publication-quality figures from simulation data
This script ONLY plots data, does NOT run simulation
Reads data from JSON files generated by JEM2025_simulation_complete.py
"""

import numpy as np
import matplotlib.pyplot as plt
import json
import os

# Set publication style
plt.rcParams['font.size'] = 11
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['axes.titlesize'] = 13
plt.rcParams['legend.fontsize'] = 10
plt.rcParams['figure.dpi'] = 150
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['font.family'] = 'sans-serif'

print("="*70)
print("JEM2025 Figure Generation - Publication Quality Plots")
print("="*70)

# Device parameters for reference
LWIR_thickness = 9.0
Barrier_thickness = 4.35
VLWIR_thickness = 14.0
total_length = LWIR_thickness + Barrier_thickness + VLWIR_thickness

Eg_LWIR = 0.140
Eg_Barrier = 0.285
Eg_VLWIR = 0.091

# Check if data files exist
data_files = {
    'band_0V': 'exp_oc/band_data_V0p0V.json',
    'band_0p1V': 'exp_oc/band_data_V0p1V.json', 
    'band_minus0p1V': 'exp_oc/band_data_Vminus0p1V.json',
    'iv': 'exp_oc/iv_data.json',
    'carrier': 'exp_oc/carrier_data.json'
}

print("\nChecking for data files...")
missing_files = []
for name, filepath in data_files.items():
    if os.path.exists(filepath):
        print(f"  [OK] {filepath}")
    else:
        print(f"  [MISSING] {filepath}")
        missing_files.append(filepath)

if missing_files:
    print("\n[ERROR] Missing data files!")
    print("Please run: python exp_oc/JEM2025_simulation_complete.py")
    print("This will generate all required simulation data.")
    sys.exit(1)

print("\nAll data files found. Generating figures...")

# =============================================================================
# LOAD DATA
# =============================================================================

def load_json(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

# Load band diagram data
band_0V = load_json(data_files['band_0V'])
band_0p1V = load_json(data_files['band_0p1V'])
band_minus0p1V = load_json(data_files['band_minus0p1V'])

# Load I-V data
iv_data = load_json(data_files['iv'])

# Load carrier data
carrier_data = load_json(data_files['carrier'])

print("  Data loaded successfully")

# =============================================================================
# FIGURE 5: Band Diagrams (3 subplots)
# =============================================================================

print("\n[1/3] Generating Figure 5: Band Diagrams (3 subplots)...")

def convert_potential_to_bands(x, V, region_boundaries):
    """Convert potential to energy bands"""
    Ec = -np.array(V)  # Conduction band
    Ev = np.zeros_like(Ec)
    
    # Apply bandgaps based on position
    for i, xi in enumerate(x):
        if xi < region_boundaries['LWIR']:
            Ev[i] = Ec[i] - Eg_LWIR
        elif xi < region_boundaries['Barrier']:
            Ev[i] = Ec[i] - Eg_Barrier
        else:
            Ev[i] = Ec[i] - Eg_VLWIR
    
    return Ec, Ev

region_boundaries = {
    'LWIR': LWIR_thickness,
    'Barrier': LWIR_thickness + Barrier_thickness
}

# Create figure with 3 subplots horizontally
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

bias_configs = [
    ('0.0', band_0V, 'V = 0 V (Equilibrium)'),
    ('0.1', band_0p1V, 'V = +0.1 V (Forward)'),
    ('-0.1', band_minus0p1V, 'V = -0.1 V (Reverse)')
]

for idx, (bias_key, data, title) in enumerate(bias_configs):
    ax = axes[idx]
    x = np.array(data['x'])
    V = np.array(data['V'])
    
    # Convert to energy bands
    Ec, Ev = convert_potential_to_bands(x, V, region_boundaries)
    Ei = (Ec + Ev) / 2  # Mid-gap (intrinsic level approximation)
    
    # Plot bands
    ax.plot(x, Ec, 'b-', linewidth=2.5, label='$E_c$')
    ax.plot(x, Ev, 'r-', linewidth=2.5, label='$E_v$')
    ax.plot(x, Ei, 'g--', linewidth=2, label='$E_i$')
    
    # Add region shading
    ax.axvspan(0, LWIR_thickness, alpha=0.15, color='blue')
    ax.axvspan(LWIR_thickness, LWIR_thickness + Barrier_thickness, alpha=0.15, color='gray')
    ax.axvspan(LWIR_thickness + Barrier_thickness, min(10, max(x)), alpha=0.15, color='red')
    
    # Add interface lines
    ax.axvline(x=LWIR_thickness, color='k', linestyle='--', alpha=0.5, linewidth=1)
    ax.axvline(x=LWIR_thickness + Barrier_thickness, color='k', linestyle='--', alpha=0.5, linewidth=1)
    
    # Labels and formatting
    ax.set_xlabel('Position (µm)', fontsize=11)
    if idx == 0:
        ax.set_ylabel('Energy (eV)', fontsize=11)
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.legend(loc='best', fontsize=9)
    ax.grid(True, alpha=0.3)
    ax.set_xlim(0, 10)
    
    # Add region labels for first subplot only
    if idx == 0:
        ax.text(LWIR_thickness/2, max(Ec)+0.03, 'LWIR', ha='center', fontsize=8,
                bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.7))
        ax.text(LWIR_thickness + Barrier_thickness/2, max(Ec)+0.03, 'Barrier', ha='center', fontsize=8,
                bbox=dict(boxstyle='round', facecolor='lightgray', alpha=0.7))
        ax.text(min(LWIR_thickness + Barrier_thickness + 2, 9), max(Ec)+0.03, 'VLWIR', ha='center', fontsize=8,
                bbox=dict(boxstyle='round', facecolor='lightcoral', alpha=0.7))

plt.suptitle('Figure 5: Band Diagrams at 100K', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('exp_oc/Figure5_Band_Diagrams_All_Biases.png', dpi=300, bbox_inches='tight')
print("  Saved: exp_oc/Figure5_Band_Diagrams_All_Biases.png")
plt.close()

# =============================================================================
# FIGURE 6a: I-V Characteristics
# =============================================================================

print("\n[2/3] Generating Figure 6a: I-V Characteristics...")

fig, ax = plt.subplots(figsize=(10, 7))

v = np.array(iv_data['voltage'])
j = np.abs(np.array(iv_data['current']))

# Plot simulation data
ax.semilogy(v, j, 'bo-', linewidth=2.5, markersize=8, label='Simulation (VBO=0meV)')

# Add Rule 07 lines
Rule07_VLWIR = 0.0539
Rule07_LWIR = 0.0001
ax.axhline(y=Rule07_VLWIR, color='r', linestyle='--', linewidth=2, 
           label=f'Rule 07 VLWIR (14µm)')
ax.axhline(y=Rule07_LWIR, color='orange', linestyle='--', linewidth=2, 
           label=f'Rule 07 LWIR (9µm)')

# Set axis limits as specified in paper
ax.set_xlim(-0.4, 0.4)
ax.set_ylim(1e-8, 1e-1)

ax.set_xlabel('Bias Voltage (V)', fontsize=12)
ax.set_ylabel('Dark Current Density (A/cm²)', fontsize=12)
ax.set_title('Figure 6a: I-V Characteristics at 100K', fontsize=13, fontweight='bold')
ax.legend(loc='lower right', framealpha=0.9)
ax.grid(True, alpha=0.3, which='both')

# Add text annotation for dark current at 0V
j_eq = j[np.argmin(np.abs(v))]
ax.text(0, 3e-8, f'Dark Current @ V=0V:\nJ = {j_eq:.2e} A/cm²',
        bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.8), 
        fontsize=10, ha='center')

plt.tight_layout()
plt.savefig('exp_oc/Figure6a_IV_Characteristics.png', dpi=300, bbox_inches='tight')
print("  Saved: exp_oc/Figure6a_IV_Characteristics.png")
plt.close()

# =============================================================================
# FIGURE 6b: Carrier Concentration Distribution
# =============================================================================

print("\n[3/3] Generating Figure 6b: Carrier Concentration Distribution...")

fig, ax = plt.subplots(figsize=(10, 7))

x = np.array(carrier_data['x'])
n = np.array(carrier_data['n'])
p = np.array(carrier_data['p'])

# Plot both electrons and holes
line1 = ax.semilogy(x, n, 'b-', linewidth=2.5, label='Electrons (n)')
line2 = ax.semilogy(x, p, 'r-', linewidth=2.5, label='Holes (p)')

# Add doping reference lines (horizontal dotted lines in each region)
# These show the expected majority carrier concentration
ax.axhline(y=2.46e14, xmin=0, xmax=LWIR_thickness/20, 
           color='blue', linestyle=':', alpha=0.6, linewidth=1.5)
ax.axhline(y=5e15, xmin=LWIR_thickness/20, xmax=(LWIR_thickness+Barrier_thickness)/20,
           color='gray', linestyle=':', alpha=0.6, linewidth=1.5)
ax.axhline(y=5e14, xmin=(LWIR_thickness+Barrier_thickness)/20, xmax=1,
           color='red', linestyle=':', alpha=0.6, linewidth=1.5)

# Add region shading
ax.axvspan(0, LWIR_thickness, alpha=0.1, color='blue', label='LWIR')
ax.axvspan(LWIR_thickness, LWIR_thickness + Barrier_thickness, alpha=0.1, color='gray', label='Barrier')
ax.axvspan(LWIR_thickness + Barrier_thickness, total_length, alpha=0.1, color='red', label='VLWIR')

# Add interface lines
ax.axvline(x=LWIR_thickness, color='k', linestyle='--', alpha=0.4, linewidth=1)
ax.axvline(x=LWIR_thickness + Barrier_thickness, color='k', linestyle='--', alpha=0.4, linewidth=1)

# Set axis limits as specified
ax.set_xlim(0, 20)
ax.set_ylim(1e4, 1e16)

ax.set_xlabel('Position (µm)', fontsize=12)
ax.set_ylabel('Carrier Concentration (cm⁻³)', fontsize=12)
ax.set_title('Figure 6b: Carrier Concentration Distribution at Equilibrium (100K)', 
             fontsize=13, fontweight='bold')
ax.legend(loc='best', framealpha=0.9)
ax.grid(True, alpha=0.3, which='both')

plt.tight_layout()
plt.savefig('exp_oc/Figure6b_Carrier_Concentration.png', dpi=300, bbox_inches='tight')
print("  Saved: exp_oc/Figure6b_Carrier_Concentration.png")
plt.close()

# =============================================================================
# SUMMARY
# =============================================================================

print("\n" + "="*70)
print("FIGURE GENERATION COMPLETE")
print("="*70)
print("\nGenerated publication-quality figures:")
print("  [1] Figure5_Band_Diagrams_All_Biases.png")
print("      - 3 subplots: V=0V, +0.1V, -0.1V")
print("      - Shows Ec, Ev, Ei")
print("      - X-axis: 0-10 µm")
print("")
print("  [2] Figure6a_IV_Characteristics.png")
print("      - I-V curve with Rule 07 comparison")
print("      - X-axis: -0.4 to +0.4 V")
print("      - Y-axis: 10^-8 to 10^-1 A/cm² (log scale)")
print("")
print("  [3] Figure6b_Carrier_Concentration.png")
print("      - Electrons and holes on same plot")
print("      - X-axis: 0-20 µm")
print("      - Y-axis: 10^4 to 10^16 cm^-3 (log scale)")
print("")
print("All figures saved to exp_oc/ directory")
print("="*70)

# Also display key results
print("\n[Key Results]")
print(f"  Dark current at 0V: {j_eq:.4e} A/cm²")
print(f"  Rule 07 VLWIR: {Rule07_VLWIR:.4e} A/cm²")
print(f"  Ratio: {Rule07_VLWIR/j_eq:.2e}x better than Rule 07")
print("="*70)
